# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  workflow_call: 
    inputs:
      upload_path:
        description: 'Path to the static content to deploy'
        required: false
        default: './docs'
        type: string
      node_version:
        description: 'Node.js version to use'
        required: false
        default: '16.x'
        type: string

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install Node Modules
        run: npm ci

      - name: Build Docs
        run: npm run generate-docs

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ inputs.upload_path }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1